services:
  backend:
    build: .
    container_name: django-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - .dockerignore
            - .env
            - .gitignore
            - compose.yaml
            - Dockerfile
            - LICENSE
            - README.md
            - requirements.txt
        - action: rebuild
          path: requirements.txt
    
