# Generated by Django 5.1.4 on 2025-01-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=33, verbose_name='Last/Family Name')),
                ('first_name', models.CharField(blank=True, max_length=33, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=33, verbose_name='Middle Name')),
                ('gender', models.CharField(max_length=6)),
                ('birth_date', models.DateField(blank=True, verbose_name='Birth Date')),
                ('birth_city', models.CharField(blank=True, max_length=33, verbose_name='Birth City')),
                ('birth_country', models.CharField(max_length=40, verbose_name='Birth Country')),
                ('eligibility_country', models.CharField(blank=True, max_length=40, verbose_name='Eligibility Country')),
                ('entrant_photograph', models.ImageField(upload_to='photographs', verbose_name='Entrant Photograph')),
                ('mailing_address', models.CharField(max_length=245, verbose_name='Mailing Address')),
                ('residence_country', models.CharField(max_length=40, verbose_name='Residence Country')),
                ('phone_number', models.CharField(max_length=33, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('education_level', models.CharField(max_length=33, verbose_name='Education Level')),
                ('marital_status', models.CharField(max_length=85, verbose_name='Marital Status')),
                ('children_number', models.PositiveSmallIntegerField()),
                ('confirmation_number', models.CharField(blank=True, max_length=16, verbose_name='Confirmation Number')),
                ('digital_signature', models.CharField(blank=True, max_length=40, verbose_name='Digital Signature')),
            ],
        ),
    ]
