# Generated by Django 5.1.4 on 2025-01-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_care_of', models.CharField(blank=True, max_length=33, verbose_name='In Care Of')),
                ('address_line_one', models.CharField(max_length=33, verbose_name='Address Line 1')),
                ('address_line_two', models.CharField(blank=True, max_length=33, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=33, verbose_name='City/Town')),
                ('province', models.CharField(max_length=33, verbose_name='District/County/Province/State')),
                ('zip_code', models.CharField(blank=True, max_length=33, verbose_name='Postal Code/Zip Code')),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='entrants',
            name='mailing_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry_form.mailingaddress'),
        ),
    ]
