# Generated by Django 5.1.4 on 2025-01-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrant',
            old_name='last_name',
            new_name='last_Name',
        ),
        migrations.RenameField(
            model_name='mailingaddress',
            old_name='zip_code',
            new_name='zip_Code',
        ),
    ]
