# Generated by Django 5.1.4 on 2025-01-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_form', '0002_rename_last_name_entrant_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='confirmation_Number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='digital_Signature',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
